/*****************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by xfc_map_parser
 * from the NPL output file(s) bcm78800_a0_cna_6_5_35_0_0_sf_match_id_info.yml
 * for device bcm78800_a0 and variant cna_6_5_35_0_0.
 * Edits to this file will be lost when it is regenerated.
 *
 *
 * Copyright 2018-2026 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * Tool Path: $SDK/INTERNAL/fltg/xfc_map_parser
 *
 ****************************************************************/


#include <bcmpkt/bcmpkt_rxpmd_match_id.h>
#include <bcmpkt/xfcr/bcm78800_a0/cna_6_5_35_0_0/bcm78800_a0_cna_6_5_35_0_0_bcmpkt_rxpmd_match_id_defs.h>

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l2_hdr_itag[1] =
{
    0x14,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l2_hdr_l2[1] =
{
    0x1e,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l2_hdr_otag[1] =
{
    0x18,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_arp[1] =
{
    0x4,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ethertype[1] =
{
    0x3d7eb7fe,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_icmp[2] =
{
    0x80100010,
    0x8000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ifa_header[2] =
{
    0x7e0,
    0x3f,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ifa_metadata_base[2] =
{
    0x500,
    0x28,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ipv4[2] =
{
    0xc006b7f8,
    0x35bf,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ipv6[2] =
{
    0xd780000,
    0x6bc000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_rarp[1] =
{
    0x10000000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_tcp_first_4bytes[2] =
{
    0x6031c0,
    0x3018e,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_tcp_last_16bytes[2] =
{
    0x402180,
    0x2010c,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_udp[2] =
{
    0x5028600,
    0x281430,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_unknown_l3[1] =
{
    0x20000000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_unknown_l4[2] =
{
    0x8040000,
    0x402000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_unknown_l5[2] =
{
    0x4020000,
    0x201000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l2_hdr_itag[1] =
{
    0x28,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l2_hdr_l2[1] =
{
    0x3e,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l2_hdr_otag[1] =
{
    0x30,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_arp[1] =
{
    0x4,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ethertype[2] =
{
    0x9ffd67fe,
    0xfafd7,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_icmp[1] =
{
    0x400010,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ifa_header[1] =
{
    0x1f8007e0,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ifa_metadata_base[1] =
{
    0x14000500,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ipv4[1] =
{
    0x1d67f8,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ipv6[2] =
{
    0x9fe00000,
    0x3afd7,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_rarp[2] =
{
    0x0,
    0x40000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_seg_rout_ext_1[2] =
{
    0x0,
    0x1d7,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_tcp_first_4bytes[2] =
{
    0x70061c0,
    0xc06,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_tcp_last_16bytes[2] =
{
    0x6004180,
    0x804,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_udp[2] =
{
    0x180d0600,
    0x1a0d0,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_unknown_l3[2] =
{
    0x0,
    0x80000,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_unknown_l4[2] =
{
    0x100000,
    0x20300,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_unknown_l5[2] =
{
    0x40000,
    0x8040,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_vxlan[2] =
{
    0x80000,
    0x10080,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_sys_hdr_ep_nih[1] =
{
    0x4,
};

static uint32_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_sys_hdr_loopback[1] =
{
    0x8,
};


static bcmpkt_rxpmd_match_id_db_t
bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_db[BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_COUNT] = {
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_ITAG */
        .name         = "EGRESS_PKT_FWD_L2_HDR_ITAG",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 18,
        .pminbit      = 16,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_L2 */
        .name         = "EGRESS_PKT_FWD_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 18,
        .pminbit      = 16,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_NONE */
        .name         = "EGRESS_PKT_FWD_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 2,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 18,
        .pminbit      = 16,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L2_HDR_OTAG */
        .name         = "EGRESS_PKT_FWD_L2_HDR_OTAG",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 18,
        .pminbit      = 16,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_ARP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_ARP",
        .match        = 0x200,
        .match_mask   = 0x618,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_ETHERTYPE */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_ICMP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_ICMP",
        .match        = 0x600,
        .match_mask   = 0x600,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x3,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IFA_HEADER */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IFA_HEADER",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IFA_METADATA_BASE */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IFA_METADATA_BASE",
        .match        = 0x210,
        .match_mask   = 0x610,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IPV4 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IPV4",
        .match        = 0x80,
        .match_mask   = 0x80,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 7,
        .minbit       = 7,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_IPV6 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_IPV6",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_NONE */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7ff,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_RARP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x600,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x2,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_SEG_ROUT_EXT_1 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_SEG_ROUT_EXT_1",
        .match        = 0x208,
        .match_mask   = 0x618,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x6,
        .match_mask   = 0x6,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UDP */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UDP",
        .match        = 0x2,
        .match_mask   = 0x6,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x40,
        .match_mask   = 0x40,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x100,
        .match_mask   = 0x102,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x102,
        .match_mask   = 0x106,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_FWD_L3_L4_HDR_VXLAN */
        .name         = "EGRESS_PKT_FWD_L3_L4_HDR_VXLAN",
        .match        = 0x20,
        .match_mask   = 0x20,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 5,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_SYS_HDR_EP_NIH */
        .name         = "EGRESS_PKT_SYS_HDR_EP_NIH",
        .match        = 0x2,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x2,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_SYS_HDR_LOOPBACK */
        .name         = "EGRESS_PKT_SYS_HDR_LOOPBACK",
        .match        = 0x1,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_SYS_HDR_NONE */
        .name         = "EGRESS_PKT_SYS_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 1,
        .pminbit      = 0,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_ITAG */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_ITAG",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 4,
        .pminbit      = 2,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_L2 */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 4,
        .pminbit      = 2,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_NONE */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 2,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 4,
        .pminbit      = 2,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L2_HDR_OTAG */
        .name         = "EGRESS_PKT_TUNNEL_L2_HDR_OTAG",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 4,
        .pminbit      = 2,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_ARP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_ARP",
        .match        = 0x200,
        .match_mask   = 0x618,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_ETHERTYPE */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_ICMP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_ICMP",
        .match        = 0x600,
        .match_mask   = 0x600,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x3,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IFA_HEADER */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IFA_HEADER",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IFA_METADATA_BASE */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IFA_METADATA_BASE",
        .match        = 0x210,
        .match_mask   = 0x610,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV4 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV4",
        .match        = 0x80,
        .match_mask   = 0x80,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 7,
        .minbit       = 7,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV6 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_IPV6",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_NONE */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7ff,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_RARP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x600,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x2,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_SEG_ROUT_EXT_1 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_SEG_ROUT_EXT_1",
        .match        = 0x208,
        .match_mask   = 0x618,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x6,
        .match_mask   = 0x6,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UDP */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UDP",
        .match        = 0x2,
        .match_mask   = 0x6,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x40,
        .match_mask   = 0x40,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x100,
        .match_mask   = 0x102,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x102,
        .match_mask   = 0x106,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_EGRESS_PKT_TUNNEL_L3_L4_HDR_VXLAN */
        .name         = "EGRESS_PKT_TUNNEL_L3_L4_HDR_VXLAN",
        .match        = 0x20,
        .match_mask   = 0x20,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 5,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_ITAG */
        .name         = "INGRESS_PKT_INNER_L2_HDR_ITAG",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 18,
        .pminbit      = 16,
        .zone_minbit  = 11,
        .arc_id_mask  = 0x3800,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l2_hdr_itag,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_L2 */
        .name         = "INGRESS_PKT_INNER_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 18,
        .pminbit      = 16,
        .zone_minbit  = 11,
        .arc_id_mask  = 0x3800,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l2_hdr_l2,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_NONE */
        .name         = "INGRESS_PKT_INNER_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 2,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 18,
        .pminbit      = 16,
        .zone_minbit  = 11,
        .arc_id_mask  = 0x3800,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L2_HDR_OTAG */
        .name         = "INGRESS_PKT_INNER_L2_HDR_OTAG",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 18,
        .match_minbit = 16,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 18,
        .pminbit      = 16,
        .zone_minbit  = 11,
        .arc_id_mask  = 0x3800,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l2_hdr_otag,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_ARP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_ARP",
        .match        = 0x200,
        .match_mask   = 0x618,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_arp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_ETHERTYPE */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ethertype,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_ICMP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_ICMP",
        .match        = 0x600,
        .match_mask   = 0x600,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x3,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_icmp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IFA_HEADER */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IFA_HEADER",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ifa_header,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IFA_METADATA_BASE */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IFA_METADATA_BASE",
        .match        = 0x210,
        .match_mask   = 0x610,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ifa_metadata_base,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IPV4 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IPV4",
        .match        = 0x80,
        .match_mask   = 0x80,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 7,
        .minbit       = 7,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ipv4,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_IPV6 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_IPV6",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_ipv6,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_NONE */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7ff,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_RARP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x600,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x2,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_rarp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_tcp_first_4bytes,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x6,
        .match_mask   = 0x6,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_tcp_last_16bytes,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UDP */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UDP",
        .match        = 0x2,
        .match_mask   = 0x6,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_udp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x40,
        .match_mask   = 0x40,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_unknown_l3,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x100,
        .match_mask   = 0x102,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_unknown_l4,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "INGRESS_PKT_INNER_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x102,
        .match_mask   = 0x106,
        .match_maxbit = 29,
        .match_minbit = 19,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 29,
        .pminbit      = 19,
        .zone_minbit  = 14,
        .arc_id_mask  = 0xfc000,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_inner_l3_l4_hdr_unknown_l5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_ITAG */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_ITAG",
        .match        = 0x2,
        .match_mask   = 0x2,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 4,
        .pminbit      = 2,
        .zone_minbit  = 2,
        .arc_id_mask  = 0x1c,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l2_hdr_itag,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_L2 */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_L2",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 4,
        .pminbit      = 2,
        .zone_minbit  = 2,
        .arc_id_mask  = 0x1c,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l2_hdr_l2,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_NONE */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 2,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 4,
        .pminbit      = 2,
        .zone_minbit  = 2,
        .arc_id_mask  = 0x1c,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L2_HDR_OTAG */
        .name         = "INGRESS_PKT_OUTER_L2_HDR_OTAG",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 4,
        .match_minbit = 2,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 4,
        .pminbit      = 2,
        .zone_minbit  = 2,
        .arc_id_mask  = 0x1c,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l2_hdr_otag,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_ARP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_ARP",
        .match        = 0x200,
        .match_mask   = 0x618,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_arp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_ETHERTYPE */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_ETHERTYPE",
        .match        = 0x1,
        .match_mask   = 0x1,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 0,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ethertype,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_ICMP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_ICMP",
        .match        = 0x600,
        .match_mask   = 0x600,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x3,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_icmp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IFA_HEADER */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IFA_HEADER",
        .match        = 0x10,
        .match_mask   = 0x10,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 4,
        .minbit       = 4,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ifa_header,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IFA_METADATA_BASE */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IFA_METADATA_BASE",
        .match        = 0x210,
        .match_mask   = 0x610,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ifa_metadata_base,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IPV4 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IPV4",
        .match        = 0x80,
        .match_mask   = 0x80,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 7,
        .minbit       = 7,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ipv4,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_IPV6 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_IPV6",
        .match        = 0x8,
        .match_mask   = 0x8,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 3,
        .minbit       = 3,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_ipv6,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_NONE */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x7ff,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_RARP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_RARP",
        .match        = 0x400,
        .match_mask   = 0x600,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x2,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_rarp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_SEG_ROUT_EXT_1 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_SEG_ROUT_EXT_1",
        .match        = 0x208,
        .match_mask   = 0x618,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 10,
        .minbit       = 9,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_seg_rout_ext_1,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_TCP_FIRST_4BYTES */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_TCP_FIRST_4BYTES",
        .match        = 0x4,
        .match_mask   = 0x4,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 2,
        .minbit       = 2,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_tcp_first_4bytes,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_TCP_LAST_16BYTES */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_TCP_LAST_16BYTES",
        .match        = 0x6,
        .match_mask   = 0x6,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_tcp_last_16bytes,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UDP */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UDP",
        .match        = 0x2,
        .match_mask   = 0x6,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 1,
        .minbit       = 1,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_udp,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L3 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L3",
        .match        = 0x40,
        .match_mask   = 0x40,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 6,
        .minbit       = 6,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_unknown_l3,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L4 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L4",
        .match        = 0x100,
        .match_mask   = 0x102,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_unknown_l4,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L5 */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_UNKNOWN_L5",
        .match        = 0x102,
        .match_mask   = 0x106,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 8,
        .minbit       = 8,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_unknown_l5,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_OUTER_L3_L4_HDR_VXLAN */
        .name         = "INGRESS_PKT_OUTER_L3_L4_HDR_VXLAN",
        .match        = 0x20,
        .match_mask   = 0x20,
        .match_maxbit = 15,
        .match_minbit = 5,
        .maxbit       = 5,
        .minbit       = 5,
        .value        = 0x1,
        .pmaxbit      = 15,
        .pminbit      = 5,
        .zone_minbit  = 5,
        .arc_id_mask  = 0x7e0,
        .num_zone_bmp_words = 2,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_outer_l3_l4_hdr_vxlan,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_SYS_HDR_EP_NIH */
        .name         = "INGRESS_PKT_SYS_HDR_EP_NIH",
        .match        = 0x2,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x2,
        .pmaxbit      = 1,
        .pminbit      = 0,
        .zone_minbit  = 0,
        .arc_id_mask  = 0x3,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_sys_hdr_ep_nih,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_SYS_HDR_LOOPBACK */
        .name         = "INGRESS_PKT_SYS_HDR_LOOPBACK",
        .match        = 0x1,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x1,
        .pmaxbit      = 1,
        .pminbit      = 0,
        .zone_minbit  = 0,
        .arc_id_mask  = 0x3,
        .num_zone_bmp_words = 1,
        .zone_bmp = bcm78800_a0_cna_6_5_35_0_0_rxpmd_arc_ingress_pkt_sys_hdr_loopback,

    },
    {
        /* BCM78800_A0_CNA_6_5_35_0_0_RXPMD_MATCH_ID_INGRESS_PKT_SYS_HDR_NONE */
        .name         = "INGRESS_PKT_SYS_HDR_NONE",
        .match        = 0x0,
        .match_mask   = 0x3,
        .match_maxbit = 1,
        .match_minbit = 0,
        .maxbit       = 1,
        .minbit       = 0,
        .value        = 0x0,
        .pmaxbit      = 1,
        .pminbit      = 0,
        .zone_minbit  = 0,
        .arc_id_mask  = 0x3,

    },
};

static bcmpkt_rxpmd_match_id_db_info_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_db_info = {
    .num_entries = 88,
    .db = bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_db
};
bcmpkt_rxpmd_match_id_db_info_t * bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_db_info_get(void) {
    return &bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_db_info;
}

static shr_enum_map_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_map[] = {
    BCM78800_A0_CNA_6_5_35_0_0_BCMPKT_RXPMD_MATCH_ID_FIELD_NAME_MAP_INIT
};

static bcmpkt_rxpmd_match_id_map_info_t bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_map_info = {
    .num_entries = 88,
    .map = bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_map
};

bcmpkt_rxpmd_match_id_map_info_t * bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_map_info_get(void) {
    return &bcm78800_a0_cna_6_5_35_0_0_rxpmd_match_id_map_info;
}
