/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/regs/xgs/generate-pmd.pl
 *
 *
 * Copyright 2018-2026 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * This file provides PMD field defines for BCM78800_A0.
 *
 ******************************************************************************/

#ifndef BCM78800_A0_PMD_FIELD_H
#define BCM78800_A0_PMD_FIELD_H

/* RXPMD defines */
#define BCM78800_A0_RXPMD_ARC_ID_HI                                  0
#define BCM78800_A0_RXPMD_ARC_ID_LO                                  1
#define BCM78800_A0_RXPMD_CNG                                        2
#define BCM78800_A0_RXPMD_COPY_TO_CPU                                3
#define BCM78800_A0_RXPMD_DMA_HEADER_VERSION                         4
#define BCM78800_A0_RXPMD_DOP_TRIGGER                                5
#define BCM78800_A0_RXPMD_EGR_ZONE_REMAP_CTRL                        6
#define BCM78800_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_3_0_OR_MIRROR_ENCAP_INDEX 7
#define BCM78800_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_6_4                 8
#define BCM78800_A0_RXPMD_FLEX_DATA                                  9
#define BCM78800_A0_RXPMD_INT_CN                                     10
#define BCM78800_A0_RXPMD_IP_ROUTED                                  11
#define BCM78800_A0_RXPMD_L3ONLY                                     12
#define BCM78800_A0_RXPMD_MPB_FLEX_DATA_TYPE                         13
#define BCM78800_A0_RXPMD_MULTICAST                                  14
#define BCM78800_A0_RXPMD_PKT_LENGTH                                 15
#define BCM78800_A0_RXPMD_QUEUE_NUM                                  16
#define BCM78800_A0_RXPMD_REPLICATION_OR_NHOP_INDEX                  17
#define BCM78800_A0_RXPMD_SRC_PORT_NUM                               18
#define BCM78800_A0_RXPMD_SWITCH                                     19
#define BCM78800_A0_RXPMD_TRUNCATE_CPU_COPY                          20
#define BCM78800_A0_RXPMD_UC_SW_COPY_DROPPED                         21
#define BCM78800_A0_RXPMD_COUNT                                      22

/* RXPMD name map */
#define BCM78800_A0_RXPMD_NAME_MAP_INIT \
    {"ARC_ID_HI", BCM78800_A0_RXPMD_ARC_ID_HI}, \
    {"ARC_ID_LO", BCM78800_A0_RXPMD_ARC_ID_LO}, \
    {"CNG", BCM78800_A0_RXPMD_CNG}, \
    {"COPY_TO_CPU", BCM78800_A0_RXPMD_COPY_TO_CPU}, \
    {"DMA_HEADER_VERSION", BCM78800_A0_RXPMD_DMA_HEADER_VERSION}, \
    {"DOP_TRIGGER", BCM78800_A0_RXPMD_DOP_TRIGGER}, \
    {"EGR_ZONE_REMAP_CTRL", BCM78800_A0_RXPMD_EGR_ZONE_REMAP_CTRL}, \
    {"EPARSE_EXTRACT_OFFSETS_3_0_OR_MIRROR_ENCAP_INDEX", BCM78800_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_3_0_OR_MIRROR_ENCAP_INDEX}, \
    {"EPARSE_EXTRACT_OFFSETS_6_4", BCM78800_A0_RXPMD_EPARSE_EXTRACT_OFFSETS_6_4}, \
    {"FLEX_DATA", BCM78800_A0_RXPMD_FLEX_DATA}, \
    {"INT_CN", BCM78800_A0_RXPMD_INT_CN}, \
    {"IP_ROUTED", BCM78800_A0_RXPMD_IP_ROUTED}, \
    {"L3ONLY", BCM78800_A0_RXPMD_L3ONLY}, \
    {"MPB_FLEX_DATA_TYPE", BCM78800_A0_RXPMD_MPB_FLEX_DATA_TYPE}, \
    {"MULTICAST", BCM78800_A0_RXPMD_MULTICAST}, \
    {"PKT_LENGTH", BCM78800_A0_RXPMD_PKT_LENGTH}, \
    {"QUEUE_NUM", BCM78800_A0_RXPMD_QUEUE_NUM}, \
    {"REPLICATION_OR_NHOP_INDEX", BCM78800_A0_RXPMD_REPLICATION_OR_NHOP_INDEX}, \
    {"SRC_PORT_NUM", BCM78800_A0_RXPMD_SRC_PORT_NUM}, \
    {"SWITCH", BCM78800_A0_RXPMD_SWITCH}, \
    {"TRUNCATE_CPU_COPY", BCM78800_A0_RXPMD_TRUNCATE_CPU_COPY}, \
    {"UC_SW_COPY_DROPPED", BCM78800_A0_RXPMD_UC_SW_COPY_DROPPED}, \
    {"COUNT", BCM78800_A0_RXPMD_COUNT}

/* TXPMD defines */
#define BCM78800_A0_TXPMD_CELL_ERROR                                 0
#define BCM78800_A0_TXPMD_CELL_LENGTH                                1
#define BCM78800_A0_TXPMD_CNG                                        2
#define BCM78800_A0_TXPMD_COPY_TO_CPU                                3
#define BCM78800_A0_TXPMD_COPY_TO_DEBUG                              4
#define BCM78800_A0_TXPMD_COS                                        5
#define BCM78800_A0_TXPMD_DST_SUBPORT_NUM                            6
#define BCM78800_A0_TXPMD_EOP                                        7
#define BCM78800_A0_TXPMD_HEADER_TYPE                                8
#define BCM78800_A0_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN            9
#define BCM78800_A0_TXPMD_IEEE1588_ONE_STEP_ENABLE                   10
#define BCM78800_A0_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM                11
#define BCM78800_A0_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET              12
#define BCM78800_A0_TXPMD_INPUT_PRI                                  13
#define BCM78800_A0_TXPMD_LOCAL_DEST_PORT                            14
#define BCM78800_A0_TXPMD_PKT_LENGTH                                 15
#define BCM78800_A0_TXPMD_RQE_Q_NUM                                  16
#define BCM78800_A0_TXPMD_SET_L2BM                                   17
#define BCM78800_A0_TXPMD_SOP                                        18
#define BCM78800_A0_TXPMD_SPAP                                       19
#define BCM78800_A0_TXPMD_SPID                                       20
#define BCM78800_A0_TXPMD_SPID_OVERRIDE                              21
#define BCM78800_A0_TXPMD_START                                      22
#define BCM78800_A0_TXPMD_TS_ACTION_LSB                              23
#define BCM78800_A0_TXPMD_TS_ACTION_MSB                              24
#define BCM78800_A0_TXPMD_TS_TYPE                                    25
#define BCM78800_A0_TXPMD_TX_TS                                      26
#define BCM78800_A0_TXPMD_UDP_CHECKSUM_OFFSET                        27
#define BCM78800_A0_TXPMD_UDP_CHECKSUM_UPDATE_ENABLE                 28
#define BCM78800_A0_TXPMD_UNICAST                                    29
#define BCM78800_A0_TXPMD_UNICAST_PKT                                30
#define BCM78800_A0_TXPMD_WRED_MARK_ELIGIBLE                         31
#define BCM78800_A0_TXPMD_WRED_RESPONSIVE                            32
#define BCM78800_A0_TXPMD_COUNT                                      33

/* TXPMD name map */
#define BCM78800_A0_TXPMD_NAME_MAP_INIT \
    {"CELL_ERROR", BCM78800_A0_TXPMD_CELL_ERROR}, \
    {"CELL_LENGTH", BCM78800_A0_TXPMD_CELL_LENGTH}, \
    {"CNG", BCM78800_A0_TXPMD_CNG}, \
    {"COPY_TO_CPU", BCM78800_A0_TXPMD_COPY_TO_CPU}, \
    {"COPY_TO_DEBUG", BCM78800_A0_TXPMD_COPY_TO_DEBUG}, \
    {"COS", BCM78800_A0_TXPMD_COS}, \
    {"DST_SUBPORT_NUM", BCM78800_A0_TXPMD_DST_SUBPORT_NUM}, \
    {"EOP", BCM78800_A0_TXPMD_EOP}, \
    {"HEADER_TYPE", BCM78800_A0_TXPMD_HEADER_TYPE}, \
    {"IEEE1588_INGRESS_TIMESTAMP_SIGN", BCM78800_A0_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN}, \
    {"IEEE1588_ONE_STEP_ENABLE", BCM78800_A0_TXPMD_IEEE1588_ONE_STEP_ENABLE}, \
    {"IEEE1588_REGEN_UDP_CHECKSUM", BCM78800_A0_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM}, \
    {"IEEE1588_TIMESTAMP_HDR_OFFSET", BCM78800_A0_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET}, \
    {"INPUT_PRI", BCM78800_A0_TXPMD_INPUT_PRI}, \
    {"LOCAL_DEST_PORT", BCM78800_A0_TXPMD_LOCAL_DEST_PORT}, \
    {"PKT_LENGTH", BCM78800_A0_TXPMD_PKT_LENGTH}, \
    {"RQE_Q_NUM", BCM78800_A0_TXPMD_RQE_Q_NUM}, \
    {"SET_L2BM", BCM78800_A0_TXPMD_SET_L2BM}, \
    {"SOP", BCM78800_A0_TXPMD_SOP}, \
    {"SPAP", BCM78800_A0_TXPMD_SPAP}, \
    {"SPID", BCM78800_A0_TXPMD_SPID}, \
    {"SPID_OVERRIDE", BCM78800_A0_TXPMD_SPID_OVERRIDE}, \
    {"START", BCM78800_A0_TXPMD_START}, \
    {"TS_ACTION_LSB", BCM78800_A0_TXPMD_TS_ACTION_LSB}, \
    {"TS_ACTION_MSB", BCM78800_A0_TXPMD_TS_ACTION_MSB}, \
    {"TS_TYPE", BCM78800_A0_TXPMD_TS_TYPE}, \
    {"TX_TS", BCM78800_A0_TXPMD_TX_TS}, \
    {"UDP_CHECKSUM_OFFSET", BCM78800_A0_TXPMD_UDP_CHECKSUM_OFFSET}, \
    {"UDP_CHECKSUM_UPDATE_ENABLE", BCM78800_A0_TXPMD_UDP_CHECKSUM_UPDATE_ENABLE}, \
    {"UNICAST", BCM78800_A0_TXPMD_UNICAST}, \
    {"UNICAST_PKT", BCM78800_A0_TXPMD_UNICAST_PKT}, \
    {"WRED_MARK_ELIGIBLE", BCM78800_A0_TXPMD_WRED_MARK_ELIGIBLE}, \
    {"WRED_RESPONSIVE", BCM78800_A0_TXPMD_WRED_RESPONSIVE}, \
    {"COUNT", BCM78800_A0_TXPMD_COUNT}

/*!
 * \name BCM78800_A0_TXPMD_HEADER_TYPE encodings.
 * \anchor BCM78800_A0_TXPMD_HEADER_TYPE_XXX
 */
/*! \{ */
#define BCM78800_A0_TXPMD_HEADER_TYPE_RESERVED_0                     0
#define BCM78800_A0_TXPMD_HEADER_TYPE_SOBMH_FROM_INTERNAL_PORT       1
/*! \} */

/*! BCM78800_A0_TXPMD_HEADER_TYPE encoding name strings maps. */
#define BCM78800_A0_TXPMD_HEADER_TYPE_NAME_MAP_INIT \
    {"RESERVED_0", BCM78800_A0_TXPMD_HEADER_TYPE_RESERVED_0},\
    {"SOBMH_FROM_INTERNAL_PORT", BCM78800_A0_TXPMD_HEADER_TYPE_SOBMH_FROM_INTERNAL_PORT},\
    {NULL, 0}

/*!
 * \name BCM78800_A0_TXPMD_START encodings.
 * \anchor BCM78800_A0_TXPMD_START_XXX
 */
/*! \{ */
#define BCM78800_A0_TXPMD_START_RESERVED_0                           0
#define BCM78800_A0_TXPMD_START_RESERVED_1                           1
#define BCM78800_A0_TXPMD_START_INTERNAL_HEADER                      2
#define BCM78800_A0_TXPMD_START_HIGIG                                3
/*! \} */

/*! BCM78800_A0_TXPMD_START encoding name strings maps. */
#define BCM78800_A0_TXPMD_START_NAME_MAP_INIT \
    {"RESERVED_0", BCM78800_A0_TXPMD_START_RESERVED_0},\
    {"RESERVED_1", BCM78800_A0_TXPMD_START_RESERVED_1},\
    {"INTERNAL_HEADER", BCM78800_A0_TXPMD_START_INTERNAL_HEADER},\
    {"HIGIG", BCM78800_A0_TXPMD_START_HIGIG},\
    {NULL, 0}

#endif /* BCM78800_A0_PMD_FIELD_H */
