/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/regs/xgs/generate-pmd.pl
 *
 *
 * Copyright 2018-2026 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.
 *
 * This file provides PMD field defines for BCM56880_A0.
 *
 ******************************************************************************/

#ifndef BCM56880_A0_PMD_FIELD_H
#define BCM56880_A0_PMD_FIELD_H

/* RXPMD defines */
#define BCM56880_A0_RXPMD_CNG                                        0
#define BCM56880_A0_RXPMD_COPY_TO_CPU                                1
#define BCM56880_A0_RXPMD_DMA_HEADER_VERSION                         2
#define BCM56880_A0_RXPMD_EGR_ZONE_REMAP_CTRL                        3
#define BCM56880_A0_RXPMD_FLEX_DATA                                  4
#define BCM56880_A0_RXPMD_INT_CN                                     5
#define BCM56880_A0_RXPMD_IP_ROUTED                                  6
#define BCM56880_A0_RXPMD_L3ONLY                                     7
#define BCM56880_A0_RXPMD_MATCH_ID_HI                                8
#define BCM56880_A0_RXPMD_MATCH_ID_LO                                9
#define BCM56880_A0_RXPMD_MPB_FLEX_DATA_TYPE                         10
#define BCM56880_A0_RXPMD_MULTICAST                                  11
#define BCM56880_A0_RXPMD_PKT_LENGTH                                 12
#define BCM56880_A0_RXPMD_QUEUE_NUM                                  13
#define BCM56880_A0_RXPMD_REPLICATION_OR_NHOP_INDEX                  14
#define BCM56880_A0_RXPMD_SRC_PORT_NUM                               15
#define BCM56880_A0_RXPMD_SWITCH                                     16
#define BCM56880_A0_RXPMD_TRUNCATE_CPU_COPY                          17
#define BCM56880_A0_RXPMD_UC_SW_COPY_DROPPED                         18
#define BCM56880_A0_RXPMD_UNICAST_QUEUE                              19
#define BCM56880_A0_RXPMD_COUNT                                      20

/* RXPMD name map */
#define BCM56880_A0_RXPMD_NAME_MAP_INIT \
    {"CNG", BCM56880_A0_RXPMD_CNG}, \
    {"COPY_TO_CPU", BCM56880_A0_RXPMD_COPY_TO_CPU}, \
    {"DMA_HEADER_VERSION", BCM56880_A0_RXPMD_DMA_HEADER_VERSION}, \
    {"EGR_ZONE_REMAP_CTRL", BCM56880_A0_RXPMD_EGR_ZONE_REMAP_CTRL}, \
    {"FLEX_DATA", BCM56880_A0_RXPMD_FLEX_DATA}, \
    {"INT_CN", BCM56880_A0_RXPMD_INT_CN}, \
    {"IP_ROUTED", BCM56880_A0_RXPMD_IP_ROUTED}, \
    {"L3ONLY", BCM56880_A0_RXPMD_L3ONLY}, \
    {"MATCH_ID_HI", BCM56880_A0_RXPMD_MATCH_ID_HI}, \
    {"MATCH_ID_LO", BCM56880_A0_RXPMD_MATCH_ID_LO}, \
    {"MPB_FLEX_DATA_TYPE", BCM56880_A0_RXPMD_MPB_FLEX_DATA_TYPE}, \
    {"MULTICAST", BCM56880_A0_RXPMD_MULTICAST}, \
    {"PKT_LENGTH", BCM56880_A0_RXPMD_PKT_LENGTH}, \
    {"QUEUE_NUM", BCM56880_A0_RXPMD_QUEUE_NUM}, \
    {"REPLICATION_OR_NHOP_INDEX", BCM56880_A0_RXPMD_REPLICATION_OR_NHOP_INDEX}, \
    {"SRC_PORT_NUM", BCM56880_A0_RXPMD_SRC_PORT_NUM}, \
    {"SWITCH", BCM56880_A0_RXPMD_SWITCH}, \
    {"TRUNCATE_CPU_COPY", BCM56880_A0_RXPMD_TRUNCATE_CPU_COPY}, \
    {"UC_SW_COPY_DROPPED", BCM56880_A0_RXPMD_UC_SW_COPY_DROPPED}, \
    {"UNICAST_QUEUE", BCM56880_A0_RXPMD_UNICAST_QUEUE}, \
    {"COUNT", BCM56880_A0_RXPMD_COUNT}

/* TXPMD defines */
#define BCM56880_A0_TXPMD_CELL_ERROR                                 0
#define BCM56880_A0_TXPMD_CELL_LENGTH                                1
#define BCM56880_A0_TXPMD_COS                                        2
#define BCM56880_A0_TXPMD_EOP                                        3
#define BCM56880_A0_TXPMD_HEADER_TYPE                                4
#define BCM56880_A0_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN            5
#define BCM56880_A0_TXPMD_IEEE1588_ONE_STEP_ENABLE                   6
#define BCM56880_A0_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM                7
#define BCM56880_A0_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET              8
#define BCM56880_A0_TXPMD_INPUT_PRI                                  9
#define BCM56880_A0_TXPMD_LOCAL_DEST_PORT                            10
#define BCM56880_A0_TXPMD_PKT_LENGTH                                 11
#define BCM56880_A0_TXPMD_RQE_Q_NUM                                  12
#define BCM56880_A0_TXPMD_SET_L2BM                                   13
#define BCM56880_A0_TXPMD_SOP                                        14
#define BCM56880_A0_TXPMD_SPAP                                       15
#define BCM56880_A0_TXPMD_SPID                                       16
#define BCM56880_A0_TXPMD_SPID_OVERRIDE                              17
#define BCM56880_A0_TXPMD_START                                      18
#define BCM56880_A0_TXPMD_TX_TS                                      19
#define BCM56880_A0_TXPMD_UNICAST                                    20
#define BCM56880_A0_TXPMD_UNICAST_PKT                                21
#define BCM56880_A0_TXPMD_COUNT                                      22

/* TXPMD name map */
#define BCM56880_A0_TXPMD_NAME_MAP_INIT \
    {"CELL_ERROR", BCM56880_A0_TXPMD_CELL_ERROR}, \
    {"CELL_LENGTH", BCM56880_A0_TXPMD_CELL_LENGTH}, \
    {"COS", BCM56880_A0_TXPMD_COS}, \
    {"EOP", BCM56880_A0_TXPMD_EOP}, \
    {"HEADER_TYPE", BCM56880_A0_TXPMD_HEADER_TYPE}, \
    {"IEEE1588_INGRESS_TIMESTAMP_SIGN", BCM56880_A0_TXPMD_IEEE1588_INGRESS_TIMESTAMP_SIGN}, \
    {"IEEE1588_ONE_STEP_ENABLE", BCM56880_A0_TXPMD_IEEE1588_ONE_STEP_ENABLE}, \
    {"IEEE1588_REGEN_UDP_CHECKSUM", BCM56880_A0_TXPMD_IEEE1588_REGEN_UDP_CHECKSUM}, \
    {"IEEE1588_TIMESTAMP_HDR_OFFSET", BCM56880_A0_TXPMD_IEEE1588_TIMESTAMP_HDR_OFFSET}, \
    {"INPUT_PRI", BCM56880_A0_TXPMD_INPUT_PRI}, \
    {"LOCAL_DEST_PORT", BCM56880_A0_TXPMD_LOCAL_DEST_PORT}, \
    {"PKT_LENGTH", BCM56880_A0_TXPMD_PKT_LENGTH}, \
    {"RQE_Q_NUM", BCM56880_A0_TXPMD_RQE_Q_NUM}, \
    {"SET_L2BM", BCM56880_A0_TXPMD_SET_L2BM}, \
    {"SOP", BCM56880_A0_TXPMD_SOP}, \
    {"SPAP", BCM56880_A0_TXPMD_SPAP}, \
    {"SPID", BCM56880_A0_TXPMD_SPID}, \
    {"SPID_OVERRIDE", BCM56880_A0_TXPMD_SPID_OVERRIDE}, \
    {"START", BCM56880_A0_TXPMD_START}, \
    {"TX_TS", BCM56880_A0_TXPMD_TX_TS}, \
    {"UNICAST", BCM56880_A0_TXPMD_UNICAST}, \
    {"UNICAST_PKT", BCM56880_A0_TXPMD_UNICAST_PKT}, \
    {"COUNT", BCM56880_A0_TXPMD_COUNT}

/*!
 * \name BCM56880_A0_TXPMD_HEADER_TYPE encodings.
 * \anchor BCM56880_A0_TXPMD_HEADER_TYPE_XXX
 */
/*! \{ */
#define BCM56880_A0_TXPMD_HEADER_TYPE_RESERVED_0                     0
#define BCM56880_A0_TXPMD_HEADER_TYPE_SOBMH_FROM_CPU                 1
/*! \} */

/*! BCM56880_A0_TXPMD_HEADER_TYPE encoding name strings maps. */
#define BCM56880_A0_TXPMD_HEADER_TYPE_NAME_MAP_INIT \
    {"RESERVED_0", BCM56880_A0_TXPMD_HEADER_TYPE_RESERVED_0},\
    {"SOBMH_FROM_CPU", BCM56880_A0_TXPMD_HEADER_TYPE_SOBMH_FROM_CPU},\
    {NULL, 0}

/*!
 * \name BCM56880_A0_TXPMD_START encodings.
 * \anchor BCM56880_A0_TXPMD_START_XXX
 */
/*! \{ */
#define BCM56880_A0_TXPMD_START_RESERVED_0                           0
#define BCM56880_A0_TXPMD_START_RESERVED_1                           1
#define BCM56880_A0_TXPMD_START_INTERNAL_HEADER                      2
#define BCM56880_A0_TXPMD_START_HIGIG                                3
/*! \} */

/*! BCM56880_A0_TXPMD_START encoding name strings maps. */
#define BCM56880_A0_TXPMD_START_NAME_MAP_INIT \
    {"RESERVED_0", BCM56880_A0_TXPMD_START_RESERVED_0},\
    {"RESERVED_1", BCM56880_A0_TXPMD_START_RESERVED_1},\
    {"INTERNAL_HEADER", BCM56880_A0_TXPMD_START_INTERNAL_HEADER},\
    {"HIGIG", BCM56880_A0_TXPMD_START_HIGIG},\
    {NULL, 0}

#endif /* BCM56880_A0_PMD_FIELD_H */
