# -*- Kbuild -*-
#
# Linux KNET Callback module.
#
# $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
# 
# Permission is granted to use, copy, modify and/or distribute this
# software under either one of the licenses below.
# 
# License Option 1: GPL
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation (the "GPL").
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License version 2 (GPLv2) for more details.
# 
# You should have received a copy of the GNU General Public License
# version 2 (GPLv2) along with this source code.
# 
# 
# License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
# 
# This software is governed by the Broadcom Open Network Switch APIs license:
# https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
# 
# 
#

obj-m := linux-ngknetcb.o

ccflags-y := $(SDK_PMD_KFLAGS) $(LKM_CFLAGS) $(LKM_CPPFLAGS) \
             -I$(SDK)/include/ \
             -I$(SDK)/src/bcm/common/pktio/bcmdrd/include \
             -I$(SDK)/src/bcm/common/pktio/bcmltd/include \
             -I$(SDK)/src/bcm/common/pktio/bcmlrd/include \
             -I$(SDK)/src/bcm/common/pktio/bcmpkt/include \
             -I$(SDK)/systems/bde/linux/include \
             -I$(SDK)/systems/linux/kernel/modules/bcm-ngknet/include \
             -I$(SDK)/systems/linux/kernel/modules/ngknetcb/generated

linux-ngknetcb-y := $(SDK_PMD_KOBJS) \
                    ngknetcb_main.o
