/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/drd/instpkgs.pl
 *
 *
 * $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
 * 
 * Permission is granted to use, copy, modify and/or distribute this
 * software under either one of the licenses below.
 * 
 * License Option 1: GPL
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 (GPLv2) for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 (GPLv2) along with this source code.
 * 
 * 
 * License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
 * 
 * This software is governed by the Broadcom Open Network Switch APIs license:
 * https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
 * 
 * 
 */

/*
 * This file contains the complete list of supported devices.
 * No other device lists should be used anywhere in the SDK.
 */

#ifndef BCMDRD_DEVIDS_H
#define BCMDRD_DEVIDS_H

#include <bcmdrd_config.h>

/*
 * All Supported Devices and Revisions
 */

#include <soc/devids.h>

/*
 * End of Supported Devices and Revisions
 */

#endif /* BCMDRD_DEVIDS_H */

#ifdef BCMDRD_DEVLIST_ENTRY
/*
 * BCMDRD_DEVLIST_ENTRY macros.
 *
 * Before including this file, define BCMDRD_DEVLIST_ENTRY
 * as a macro to operate on the following parameters:
 *
 *     #define BCMDRD_DEVLIST_ENTRY(_nm,_vn,_dv,_rv,_md,_pi,_bd,_bc,_fn,_cn,_pf,_pd,_r0,_r1)
 *
 *     _nm: Chip Name
 *     _vn: Chip Vendor ID
 *     _dv: Chip Device ID
 *     _rv: Chip Revision
 *     _md: Chip Model
 *     _pi: Probe Information
 *     _bd: SW Base Driver
 *     _bc: SW Base Configuration
 *     _fn: SW Full Name
 *     _cn: Code Name
 *     _pf: Product Family
 *     _pd: Product Description
 *     _r0: Reserved
 *     _r1: Reserved
 *
 * Note that this macro will be undefined at the end of this file.
 */

#if BCMDRD_CONFIG_INCLUDE_BCM88860_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM88860, BROADCOM_VENDOR_ID, JERICHO3_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88860_a0, "JERICHO3", "BCM88860", "Multilayer Switch", 0, 0)

#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88860, BROADCOM_VENDOR_ID, JERICHO3_DEVICE_ID, DNXC_A1_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88860_a1, "JERICHO3", "BCM88860", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88860, BROADCOM_VENDOR_ID, JERICHO3_DEVICE_ID, DNXC_B0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88860_b0, "JERICHO3", "BCM88860", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88867_C0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88867, BROADCOM_VENDOR_ID, 0x8867, DNXC_C0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88867_c0, "JERICHO3P", "BCM88867", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88890_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88890, BROADCOM_VENDOR_ID, J3AI_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88890_a0, "J3AI", "BCM88890", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88890, BROADCOM_VENDOR_ID, J3AI_DEVICE_ID, DNXC_A1_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88890_a1, "J3AI", "BCM88890", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88890, BROADCOM_VENDOR_ID, J3AI_DEVICE_ID, DNXC_B0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88890_b0, "J3AI", "BCM88890", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88897_C0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88897, BROADCOM_VENDOR_ID, 0x8897, DNXC_C0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88897_c0, "J3AIP", "BCM88897", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88870_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88870, BROADCOM_VENDOR_ID, Q3D_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88870_a0, "Q3D", "BCM88870", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88490_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88490, BROADCOM_VENDOR_ID, Q3A_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm88490_a0, "Q3A", "BCM88490", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM884A0, BROADCOM_VENDOR_ID, Q3U_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm884a0_a0, "Q3U", "BCM884A0", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM884A5, BROADCOM_VENDOR_ID, Q3N_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88860_a0, bcm88860_a0, bcm884a5_a0, "Q3N", "BCM884A5", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM99450_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM99450, BROADCOM_VENDOR_ID, 0x9450, DNXC_A0_REV_ID,
                     0, 0,
                     bcm99450_a0, bcm99450_a0, bcm99450_a0, "BCM99450", "BCM99450", "Multilayer Switch", 0, 0)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM99420, BROADCOM_VENDOR_ID, 0x9420, DNXC_A0_REV_ID,
                     0, 0,
                     bcm99450_a0, bcm99450_a0, bcm99420_a0, "BCM99420", "BCM99420", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM99410_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM99410, BROADCOM_VENDOR_ID, 0x9410, DNXC_A0_REV_ID,
                     0, 0,
                     bcm99450_a0, bcm99450_a0, bcm99410_a0, "BCM99410", "BCM99410", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM99430_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM99430, BROADCOM_VENDOR_ID, 0x9430, DNXC_A0_REV_ID,
                     0, 0,
                     bcm99450_a0, bcm99450_a0, bcm99430_a0, "BCM99430", "BCM99430", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM994E0_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM994E0, BROADCOM_VENDOR_ID, 0x94e0, DNXC_A0_REV_ID,
                     0, 0,
                     bcm99450_a0, bcm99450_a0, bcm994e0_a0, "BCM994E0", "BCM994E0", "Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM88690_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM88690, BROADCOM_VENDOR_ID, JERICHO2_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88690_a0, "JERICHO2", "BCM88690", "Multilayer Switch", 0, 0)
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88690_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88690, BROADCOM_VENDOR_ID, JERICHO2_DEVICE_ID, DNXC_B0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88690_b0, "JERICHO2", "BCM88690", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88690, BROADCOM_VENDOR_ID, JERICHO2_DEVICE_ID, DNXC_B1_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88690_b1, "JERICHO2", "BCM88690", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88800_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88800, BROADCOM_VENDOR_ID, J2C_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88800_a0, "J2C", "BCM88800", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88820, BROADCOM_VENDOR_ID, J2C_2ND_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88820_a0, "J2C_2ND", "BCM88820", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88850_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88850, BROADCOM_VENDOR_ID, J2P_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88850_a0, "J2P", "BCM88850", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88830_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88830, BROADCOM_VENDOR_ID, J2X_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88830_a0, "J2X", "BCM88830", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88480_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88480, BROADCOM_VENDOR_ID, Q2A_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88480_a0, "Q2A", "BCM88480", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88280, BROADCOM_VENDOR_ID, Q2U_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88280_a0, "Q2U", "BCM88280", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88290, BROADCOM_VENDOR_ID, Q2U_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88290_a0, "Q2N", "BCM88290", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88480_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88480, BROADCOM_VENDOR_ID, Q2A_DEVICE_ID, DNXC_B0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88480_b0, "Q2A", "BCM88480", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88280, BROADCOM_VENDOR_ID, Q2U_DEVICE_ID, DNXC_B0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88280_b0, "Q2U", "BCM88280", "Multilayer Switch", 0, 0)
BCMDRD_DEVLIST_ENTRY(BCM88290, BROADCOM_VENDOR_ID, Q2U_DEVICE_ID, DNXC_B0_REV_ID,
                     0, 0,
                     bcm88690_a0, bcm88690_a0, bcm88290_b0, "Q2N", "BCM88290", "Multilayer Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM88920_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM88920, BROADCOM_VENDOR_ID, RAMON3_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88920_a0, bcm88920_a0, bcm88920_a0, "RAMON3", "BCM88920", "Fabric Switch", 0, 0)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM88910, BROADCOM_VENDOR_ID, RAMON2_DEVICE_ID, DNXC_A0_REV_ID,
                     0, 0,
                     bcm88920_a0, bcm88920_a0, bcm88910_a0, "RAMON2", "BCM88910", "Fabric Switch", 0, 0)
#endif
#endif
#if BCMDRD_CONFIG_INCLUDE_BCM99470_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM99470, BROADCOM_VENDOR_ID, 0x9470, DNXC_A0_REV_ID,
                     0, 0,
                     bcm99470_a0, bcm99470_a0, bcm99470_a0, "BCM99470", "BCM99470", "Fabric Switch", 0, 0)
#endif
/* End BCMDRD_DEVLIST_ENTRY Macros */
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
#undef BCMDRD_DEVLIST_INCLUDE_ALL
#endif
#ifdef BCMDRD_DEVLIST_OVERRIDE
#undef BCMDRD_DEVLIST_OVERRIDE
#endif
#undef BCMDRD_DEVLIST_ENTRY
#endif /* BCMDRD_DEVLIST_ENTRY */
