/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/drd/gen-feature.pl
 *
 *
 * $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
 * 
 * Permission is granted to use, copy, modify and/or distribute this
 * software under either one of the licenses below.
 * 
 * License Option 1: GPL
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 (GPLv2) for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 (GPLv2) along with this source code.
 * 
 * 
 * License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
 * 
 * This software is governed by the Broadcom Open Network Switch APIs license:
 * https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
 * 
 * 
 */

#ifndef BCMDRD_FEATURE_ENUM_H
#define BCMDRD_FEATURE_ENUM_H

#include <bcmdrd_config.h>

/*! \file bcmdrd_feature_enum.h */

/*!
 * Device features which are shared across all device families.
 */
typedef enum bcmdrd_feature_e {

    /*!
     * This value can be passed to \ref bcmdrd_feature_disable to
     * clear all features.
     */
    BCMDRD_FT_ALL = 0,

    /*!
     * Device is connected to an active simulator like BCMSIM and
     * typically via the PLI protocol. An active simulator supports
     * most hardware features including DMA and interrupts, but it
     * will be much slower than real hardware.
     */
    BCMDRD_FT_ACTIVE_SIM,

    /*!
     * Device includes the Broadscan network telemetry engine.
     */
    BCMDRD_FT_BROADSCAN,

    /*!
     * Device HMI is based on iProc with CMICd.
     */
    BCMDRD_FT_CMICD,

    /*!
     * Device HMI is based on iProcR with 2nd generation CMICx.
     */
    BCMDRD_FT_CMICR,

    /*!
     * Device HMI is based on iProcR with 2nd generation CMICx v2.
     */
    BCMDRD_FT_CMICR2,

    /*!
     * Device HMI is based on iProc with CMICx.
     */
    BCMDRD_FT_CMICX,

    /*!
     * Device HMI is based on iProc with CMICx v2.
     */
    BCMDRD_FT_CMICX2,

    /*!
     * Device supports Channelization over Ethernet, which enables
     * advanced traffic management for line cards via a backplane
     * control switch.
     */
    BCMDRD_FT_COE,

    /*!
     * Device supports cut-through switching, i.e. a packet may be
     * forwarded before the entire packet has been received.
     */
    BCMDRD_FT_CUT_THRU,

    /*!
     * Device supports Distributed Load Balancing across aggregated
     * links.
     */
    BCMDRD_FT_DLB,

    /*!
     * Device is connected to an emulator like Quickturn, which will
     * operate like real silicon, although many operations will be
     * slower. The emulator is often limited in scope, e.g. reduced
     * port count, no SerDes support, no embedded CPUs, etc.
     */
    BCMDRD_FT_EMUL,

    /*!
     * Device supports flex-code, which is micro-code that defines the
     * device hardware behavior. Typically, flex-code is used to
     * enable specific networking capabilities in hardware.
     */
    BCMDRD_FT_FLEXCODE,

    /*!
     * Device includes hardware flow tracking support to enable
     * IPFIX-compliant monitoring applications like BroadView.
     */
    BCMDRD_FT_FLOWTRACKER,

    /*!
     * Device includes a Hardware License Authenticator (HLA) block,
     * which provides the ability to enable additional switch features
     * by downloading a license file to the HLA block.
     */
    BCMDRD_FT_HLA,

    /*!
     * Device HMI is iProc-based.
     */
    BCMDRD_FT_IPROC,

    /*!
     * Device supports Kernel Networking (KNET) mode where the
     * low-level packet I/O is handled by a system device driver such
     * as a Linux kernel driver. When operating in KNET mode, the SDK
     * will interact with the system device driver instead of the raw
     * hardware interface when performing packet I/O.
     */
    BCMDRD_FT_KNET,

    /*!
     * Device supports hardware learning of L2 MAC addresses, i.e. the
     * source MAC address of an incoming packet is stored in a
     * hardware table alongside the ingress port number.
     */
    BCMDRD_FT_L2_HW_LEARN,

    /*!
     * Device supports the Broadcom Process Monitoring library
     * (LIB_PM), which is a standardized interface to monitor
     * voltages, currents and other low-level aspects of the device.
     */
    BCMDRD_FT_LIB_PM,

    /*!
     * Device supports the MACSEC protocol in hardware.
     */
    BCMDRD_FT_MACSEC,

    /*!
     * Host CPU bus does not support DMA. This feature typically
     * indicates that the device is connected to the host CPU via a
     * simple boot or debug interface like SPI.
     */
    BCMDRD_FT_NO_DMA,

    /*!
     * Device is connected to a passive simulator like XGSSIM. This
     * means that you always read what you write, and that DMA,
     * interrupts and any kind of HMI broadcast (SBUS, pipes, etc.)
     * are unsupported.
     */
    BCMDRD_FT_PASSIVE_SIM,

    /*!
     * Device is connected to a PHY simulator via the PHYMOD API. This
     * feature enables more comprehensive testing capabilities in a
     * simulation environment without real SerDes support.
     */
    BCMDRD_FT_PHYMOD_SIM,

    /*!
     * Device supports Visibility Compute Accelerator engine.
     */
    BCMDRD_FT_VCA,

    /*!
     * Number of features.
     */
    BCMDRD_FT_COUNT

} bcmdrd_feature_t;

/*!
 * Device features names for array initialization.
 */
#define BCMDRD_FT_NAMES \
    "ALL", \
    "ACTIVE_SIM", \
    "BROADSCAN", \
    "CMICD", \
    "CMICR", \
    "CMICR2", \
    "CMICX", \
    "CMICX2", \
    "COE", \
    "CUT_THRU", \
    "DLB", \
    "EMUL", \
    "FLEXCODE", \
    "FLOWTRACKER", \
    "HLA", \
    "IPROC", \
    "KNET", \
    "L2_HW_LEARN", \
    "LIB_PM", \
    "MACSEC", \
    "NO_DMA", \
    "PASSIVE_SIM", \
    "PHYMOD_SIM", \
    "VCA", \
    "COUNT"

#endif /* BCMDRD_FEATURE_ENUM_H */
