/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from Logical Table mapping files.
 * Edits to this file will be lost when it is regenerated.
 *
 *
 * $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
 * 
 * Permission is granted to use, copy, modify and/or distribute this
 * software under either one of the licenses below.
 * 
 * License Option 1: GPL
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 (GPLv2) for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 (GPLv2) along with this source code.
 * 
 * 
 * License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
 * 
 * This software is governed by the Broadcom Open Network Switch APIs license:
 * https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
 * 
 * 
 *
 ******************************************************************************/

#ifndef BCMLRD_CHIP_VARIANT_DEFS_H
#define BCMLRD_CHIP_VARIANT_DEFS_H

#ifndef DOXYGEN_IGNORE_AUTOGEN

#include <bcmltd/chip/bcmltd_variant_defs.h>

#define BCMLRD_VARIANT_BCM88860_A0_BASE BCMLTD_VARIANT_BCM88860_A0_BASE
#define BCMLRD_VARIANT_BCM99450_A0_BASE BCMLTD_VARIANT_BCM99450_A0_BASE
#define BCMLRD_VARIANT_BCM88690_A0_BASE BCMLTD_VARIANT_BCM88690_A0_BASE
#define BCMLRD_VARIANT_BCM88920_A0_BASE BCMLTD_VARIANT_BCM88920_A0_BASE
#define BCMLRD_VARIANT_BCM99470_A0_BASE BCMLTD_VARIANT_BCM99470_A0_BASE
#define BCMLRD_VARIANT_MAX BCMLTD_VARIANT_MAX

#endif /* DOXYGEN_IGNORE_AUTOGEN */

#endif /* BCMLRD_CHIP_VARIANT_DEFS_H */
