 /*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 *
 * $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
 * 
 * Permission is granted to use, copy, modify and/or distribute this
 * software under either one of the licenses below.
 * 
 * License Option 1: GPL
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 (GPLv2) for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 (GPLv2) along with this source code.
 * 
 * 
 * License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
 * 
 * This software is governed by the Broadcom Open Network Switch APIs license:
 * https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
 * 
 * 
 *
 * This file provides RXPMD access functions for BCM88920_A0.
 *
 ******************************************************************************/

#include <pktio_dep.h>
#include <bcmpkt/bcmpkt_rxpmd.h>
#include <bcmpkt/bcmpkt_rxpmd_internal.h>

#define WORD_MASK(_bn) (((uint32_t)0x1<<(_bn))-1)
#define WORD_FIELD_GET(_d,_s,_l) (((_d) >> (_s)) & WORD_MASK(_l))
#define WORD_FIELD_SET(_d,_s,_l,_v) (_d)=(((_d) & ~(WORD_MASK(_l) << (_s))) | (((_v) & WORD_MASK(_l)) << (_s)))
#define WORD_FIELD_MASK(_d,_s,_l) (_d)=((_d) | (WORD_MASK(_l) << (_s)))

/*******************************************************************************
 * SWFORMAT:  RXPMD
 * BLOCKS:
 * SIZE:     1536
 ******************************************************************************/
static void
bcmpkt_rxpmd_system_header_length_set(
    uint32_t * data,
    uint32_t val)
{
    data[0] = val;
}

static uint32_t
bcmpkt_rxpmd_system_header_length_get(
    uint32_t * data)
{
    uint32_t val = 0;
    val = data[0];
    return val;
}

static void
bcmpkt_rxpmd_rx_channel_set(
    uint32_t * data,
    uint32_t val)
{
    data[1] = val;
}

static uint32_t
bcmpkt_rxpmd_rx_channel_get(
    uint32_t * data)
{
    uint32_t val = 0;
    val = data[1];
    return val;
}

static uint32_t
bcmpkt_rxpmd_i_size_get(
    uint32_t *data,
    uint32_t **addr)
{
    return 16;
}

/*******************************************************************************
 * SWFORMAT:  RX_REASON
 * BLOCKS:
 * SIZE:     42
 ******************************************************************************/
void
bcm88920_a0_rx_reason_encode(
    const bcmpkt_rx_reasons_t * reasons,
    uint32_t * data)
{
}

void
bcm88920_a0_rx_reason_decode(
    const uint32_t * data,
    bcmpkt_rx_reasons_t * reasons)
{
}

void
bcm88920_a0_ep_rx_reason_encode(
    const bcmpkt_rx_reasons_t * reasons,
    uint32_t * data)
{
}

void
bcm88920_a0_ep_rx_reason_decode(
    const uint32_t * data,
    bcmpkt_rx_reasons_t * reasons)
{
}

const bcmpkt_rxpmd_fget_t bcm88920_a0_rxpmd_fget = {
{
    bcmpkt_rxpmd_system_header_length_get,
    bcmpkt_rxpmd_rx_channel_get,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
};

const bcmpkt_rxpmd_fset_t bcm88920_a0_rxpmd_fset = {
{
    bcmpkt_rxpmd_system_header_length_set,
    bcmpkt_rxpmd_rx_channel_set,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
};

const bcmpkt_rxpmd_figet_t bcm88920_a0_rxpmd_figet = {
{
    bcmpkt_rxpmd_i_size_get,
    NULL,
    NULL,
    NULL
}
};

static shr_enum_map_t bcm88920_a0_rxpmd_view_types[] = {
    {NULL, -1},
};

/* -2: unsupported, -1: global, others: view's value */
static int bcm88920_a0_rxpmd_view_infos[BCMPKT_RXPMD_FID_COUNT] = {
    -1, -1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
    -2, -2, -2
};

void
bcm88920_a0_rxpmd_view_info_get(
    bcmpkt_pmd_view_info_t * info)
{
    info->view_infos = bcm88920_a0_rxpmd_view_infos;
    info->view_types = bcm88920_a0_rxpmd_view_types;
    info->view_type_get = NULL;
}
