/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from Logical Table definition files.
 *
 * Tool: $SDK/tools/fltg/bin/fltg
 *
 * Edits to this file will be lost when it is regenerated.
 *
 *
 * $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
 * 
 * Permission is granted to use, copy, modify and/or distribute this
 * software under either one of the licenses below.
 * 
 * License Option 1: GPL
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 (GPLv2) for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 (GPLv2) along with this source code.
 * 
 * 
 * License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
 * 
 * This software is governed by the Broadcom Open Network Switch APIs license:
 * https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
 * 
 * 
 *
 ******************************************************************************/
#ifndef GEN_BCMLTD_VARIANT_ENTRY_H
#define GEN_BCMLTD_VARIANT_ENTRY_H
/* guard deliberately empty */
#endif /* GEN_BCMLTD_VARIANT_ENTRY_H */
#ifndef DOXYGEN_IGNORE_AUTOGEN
/*+replace variant */

#if BCMLTD_CONFIG_INCLUDE_BCM88860_A0_BASE == 1 || defined(BCMLTD_VARIANT_OVERRIDE)
    BCMLTD_VARIANT_ENTRY(bcm88860_a0, BCM88860_A0,, BASE,, 1, 0, NULL, 0, 0)
#endif
#if BCMLTD_CONFIG_INCLUDE_BCM99450_A0_BASE == 1 || defined(BCMLTD_VARIANT_OVERRIDE)
    BCMLTD_VARIANT_ENTRY(bcm99450_a0, BCM99450_A0,, BASE,, 1, 0, NULL, 0, 0)
#endif
#if BCMLTD_CONFIG_INCLUDE_BCM88690_A0_BASE == 1 || defined(BCMLTD_VARIANT_OVERRIDE)
    BCMLTD_VARIANT_ENTRY(bcm88690_a0, BCM88690_A0,, BASE,, 1, 0, NULL, 0, 0)
#endif
#if BCMLTD_CONFIG_INCLUDE_BCM88920_A0_BASE == 1 || defined(BCMLTD_VARIANT_OVERRIDE)
    BCMLTD_VARIANT_ENTRY(bcm88920_a0, BCM88920_A0,, BASE,, 1, 0, NULL, 0, 0)
#endif
#if BCMLTD_CONFIG_INCLUDE_BCM99470_A0_BASE == 1 || defined(BCMLTD_VARIANT_OVERRIDE)
    BCMLTD_VARIANT_ENTRY(bcm99470_a0, BCM99470_A0,, BASE,, 1, 0, NULL, 0, 0)
#endif

/*-replace*/
#endif /* DOXYGEN_IGNORE_AUTOGEN */
