# $Id: Makefile.linux-x86-smp_generic_64-2_6,v 1.5 Broadcom SDK $
#
# $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
# 
# Permission is granted to use, copy, modify and/or distribute this
# software under either one of the licenses below.
# 
# License Option 1: GPL
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation (the "GPL").
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License version 2 (GPLv2) for more details.
# 
# You should have received a copy of the GNU General Public License
# version 2 (GPLv2) along with this source code.
# 
# 
# License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
# 
# This software is governed by the Broadcom Open Network Switch APIs license:
# https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
# 
# 

CFGFLAGS += -DLONGS_ARE_64BITS
CFGFLAGS += -DPTRS_ARE_64BITS
CFGFLAGS += -DPHYS_ADDRS_ARE_64BITS
CFGFLAGS += -DSAL_SPL_LOCK_ON_IRQ

ifneq ($(ESW_CHIPS)$(LTSW_CHIPS),)
# Glibc 2.27 or later version doesn't support SVID libm error handling.
# Building tcl 8.3.3 with the new toolchain will occur errors.
export TCL840  := 1
endif

include ${SDK}/make/Makefile.linux-x86-generic-common-2_6

GCC_VER_MAJOR := $(shell $(CC) -dumpversion 2>/dev/null | cut -f1 -d.)

ifeq (,$(KFLAGS))
KFLAGS := -nostdinc -isystem $(SYSINC) -I$(KERNDIR)/include -I$(KERNDIR)/arch/x86/include -include $(AUTOCONF) -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -m64 -mtune=generic -mno-red-zone -fno-pie -mcmodel=kernel -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -fno-stack-protector -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign
ifeq "$(shell expr $(GCC_VER_MAJOR) \>= 12)" "1"
KFLAGS += -std=gnu11 -Wno-error=attributes -Wno-error=declaration-after-statement
KFLAGS += -Wno-attributes -Wno-declaration-after-statement
endif
ifneq (1,$(USE_CLANG))
KFLAGS += -funit-at-a-time -maccumulate-outgoing-args
endif
endif

LINUX_UAPI = $(LINUX_INCLUDE)/uapi
ifneq (,$(shell ls $(LINUX_UAPI) 2>/dev/null))
KFLAGS += -I$(LINUX_INCLUDE)/uapi -I$(LINUX_INCLUDE)/generated/uapi -I$(KERNDIR)/arch/x86/include/generated -I$(KERNDIR)/arch/x86/include/uapi -I$(KERNDIR)/arch/x86/include/generated/uapi
endif

ifeq "$(shell expr $(GCC_VER_MAJOR) \>= 12)" "1"
KFLAGS += -mfunction-return=thunk-extern -fpatchable-function-entry=16,16
KFLAGS += -mindirect-branch=thunk-extern -mindirect-branch-cs-prefix
# IBT: emit ENDBR so objtool "relocation to !ENDBR" warnings are resolved
KFLAGS += -fcf-protection=branch
endif

ifdef LTSW_CHIPS
# Hardware interface (see $SDKLT/bcma/sys/probe directory)
SYSTEM_INTERFACE ?= ngbde

# Turn on direct register access if running on real hardware.
ifeq (ngbde,$(SYSTEM_INTERFACE))
ifeq (,$(EXTRA_SYSTEM_INTERFACES))
LTSW_ADD_CPPFLAGS += -DBCMDRD_CONFIG_MEMMAP_DIRECT=1
endif
endif

export SYSTEM_INTERFACE
endif

# Default open source target build
OPENSRC_BUILD ?= x86_64

include ${SDK}/make/Makefile.linux-x86-common-2_6
