#ifndef BCMPKT_MHDR_DEFS_H
#define BCMPKT_MHDR_DEFS_H
/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/regs/xgs/generate-chip.pl
 *
 *
 * $Copyright: 2017-2026 Broadcom Inc. All rights reserved.
 * 
 * Permission is granted to use, copy, modify and/or distribute this
 * software under either one of the licenses below.
 * 
 * License Option 1: GPL
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation (the "GPL").
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 (GPLv2) for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * version 2 (GPLv2) along with this source code.
 * 
 * 
 * License Option 2: Broadcom Open Network Switch APIs (OpenNSA) license
 * 
 * This software is governed by the Broadcom Open Network Switch APIs license:
 * https://www.broadcom.com/products/ethernet-connectivity/software/opennsa $
 * 
 * 
 *
 * This file provides access macros for the module header included
 * in packet send to CPU.
 *
 ******************************************************************************/

#include <bcmdrd/bcmdrd_symbols.h>

/*******************************************************************************
 *
 *                    MHDR DEFINITIONS BEGIN HERE
 *
 ******************************************************************************/


/* Start of module header packet indicators */
#define BCMPKT_MHDR_SOF                 0xfb


/* Module header size (in bytes) */
#define BCMPKT_MHDR_SIZE                16


/* Module header size (in words) */
#define BCMPKT_MHDR_WSIZE               4


/*******************************************************************************
 * SWFORMAT:  MHDR
 * BLOCKS:
 * SIZE:     128
 ******************************************************************************/
#define MHDR_OFFSET 0x00000000

#define MHDR_BLKACC ()

#define MHDR_SIZE 16

/*
 * This structure should be used to declare and program MHDR.
 *
 */
typedef union MHDR_s {
    uint32_t v[4];
    uint32_t mhdr[4];
    uint32_t _mhdr;
} MHDR_t;

#define MHDR_CLR(r) sal_memset(&((r).mhdr[0]), 0, sizeof(MHDR_t))
#define MHDR_SET(r,i,d) (r).mhdr[i] = d
#define MHDR_GET(r,i) (r).mhdr[i]

/*
 * These macros can be used to access individual fields.
 *
 */
#define MHDR_PPD_DATAf_GET(r,a) bcmdrd_field_be_get((r).mhdr,4,0,63,a)
#define MHDR_PPD_DATAf_SET(r,a) bcmdrd_field_be_set((r).mhdr,4,0,63,a)
#define MHDR_PPD0_MH_OPCODEf_GET(r) ((((r).mhdr[3]) >> 8) & 0x7)
#define MHDR_PPD0_MH_OPCODEf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x7 << 8)) | ((((uint32_t)f) & 0x7) << 8))
#define MHDR_PPD0_PRESERVE_DOT1Pf_GET(r) ((((r).mhdr[3]) >> 11) & 0x1)
#define MHDR_PPD0_PRESERVE_DOT1Pf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1 << 11)) | ((((uint32_t)f) & 0x1) << 11))
#define MHDR_PPD0_PRESERVE_DSCPf_GET(r) ((((r).mhdr[3]) >> 12) & 0x1)
#define MHDR_PPD0_PRESERVE_DSCPf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1 << 12)) | ((((uint32_t)f) & 0x1) << 12))
#define MHDR_PPD0_VID_LOWf_GET(r) ((((r).mhdr[3]) >> 16) & 0xff)
#define MHDR_PPD0_VID_LOWf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0xff << 16)) | ((((uint32_t)f) & 0xff) << 16))
#define MHDR_PPD0_VID_HIGHf_GET(r) ((((r).mhdr[3]) >> 24) & 0xff)
#define MHDR_PPD0_VID_HIGHf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0xff << 24)) | ((((uint32_t)f) & 0xff) << 24))
#define MHDR_PPD0_VFIf_GET(r) (((r).mhdr[2]) & 0x1fff)
#define MHDR_PPD0_VFIf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1fff)) | (((uint32_t)f) & 0x1fff))
#define MHDR_PPD0_L3f_GET(r) ((((r).mhdr[2]) >> 21) & 0x1)
#define MHDR_PPD0_L3f_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1 << 21)) | ((((uint32_t)f) & 0x1) << 21))
#define MHDR_PPD0_MIRRORf_GET(r) ((((r).mhdr[2]) >> 24) & 0x1)
#define MHDR_PPD0_MIRRORf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1 << 24)) | ((((uint32_t)f) & 0x1) << 24))
#define MHDR_PPD0_INGRESS_TAGGEDf_GET(r) ((((r).mhdr[2]) >> 27) & 0x1)
#define MHDR_PPD0_INGRESS_TAGGEDf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1 << 27)) | ((((uint32_t)f) & 0x1) << 27))
#define MHDR_PPD0_LAG_FAILOVERf_GET(r) ((((r).mhdr[2]) >> 28) & 0x1)
#define MHDR_PPD0_LAG_FAILOVERf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1 << 28)) | ((((uint32_t)f) & 0x1) << 28))
#define MHDR_PPD0_DO_NOT_LEARNf_GET(r) ((((r).mhdr[2]) >> 29) & 0x1)
#define MHDR_PPD0_DO_NOT_LEARNf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1 << 29)) | ((((uint32_t)f) & 0x1) << 29))
#define MHDR_PPD2_PRESERVE_DOT1Pf_GET(r) ((((r).mhdr[3]) >> 2) & 0x1)
#define MHDR_PPD2_PRESERVE_DOT1Pf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1 << 2)) | ((((uint32_t)f) & 0x1) << 2))
#define MHDR_PPD2_PRESERVE_DSCPf_GET(r) ((((r).mhdr[3]) >> 3) & 0x1)
#define MHDR_PPD2_PRESERVE_DSCPf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1 << 3)) | ((((uint32_t)f) & 0x1) << 3))
#define MHDR_PPD2_VNI_HIGHf_GET(r) ((((r).mhdr[3]) >> 4) & 0x7)
#define MHDR_PPD2_VNI_HIGHf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x7 << 4)) | ((((uint32_t)f) & 0x7) << 4))
#define MHDR_PPD2_OPCODEf_GET(r) ((((r).mhdr[3]) >> 8) & 0x7)
#define MHDR_PPD2_OPCODEf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x7 << 8)) | ((((uint32_t)f) & 0x7) << 8))
#define MHDR_PPD2_LAG_FAILOVERf_GET(r) ((((r).mhdr[3]) >> 12) & 0x1)
#define MHDR_PPD2_LAG_FAILOVERf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1 << 12)) | ((((uint32_t)f) & 0x1) << 12))
#define MHDR_PPD2_DO_NOT_LEARNf_GET(r) ((((r).mhdr[3]) >> 13) & 0x1)
#define MHDR_PPD2_DO_NOT_LEARNf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1 << 13)) | ((((uint32_t)f) & 0x1) << 13))
#define MHDR_PPD2_MIRRORf_GET(r) ((((r).mhdr[3]) >> 15) & 0x1)
#define MHDR_PPD2_MIRRORf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1 << 15)) | ((((uint32_t)f) & 0x1) << 15))
#define MHDR_PPD2_SOURCE_VPf_GET(r) ((((r).mhdr[3]) >> 16) & 0x1fff)
#define MHDR_PPD2_SOURCE_VPf_SET(r,f) (r).mhdr[3]=(((r).mhdr[3] & ~((uint32_t)0x1fff << 16)) | ((((uint32_t)f) & 0x1fff) << 16))
#define MHDR_PPD2_DEST_VPf_GET(r) (((r).mhdr[2]) & 0x1fff)
#define MHDR_PPD2_DEST_VPf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1fff)) | (((uint32_t)f) & 0x1fff))
#define MHDR_PPD2_VNI_LOWf_GET(r) ((((r).mhdr[2]) >> 16) & 0x3ff)
#define MHDR_PPD2_VNI_LOWf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x3ff << 16)) | ((((uint32_t)f) & 0x3ff) << 16))
#define MHDR_PPD2_FWD_TYPEf_GET(r) ((((r).mhdr[2]) >> 26) & 0x1f)
#define MHDR_PPD2_FWD_TYPEf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1f << 26)) | ((((uint32_t)f) & 0x1f) << 26))
#define MHDR_PPD2_MULTIPOINTf_GET(r) ((((r).mhdr[2]) >> 31) & 0x1)
#define MHDR_PPD2_MULTIPOINTf_SET(r,f) (r).mhdr[2]=(((r).mhdr[2] & ~((uint32_t)0x1 << 31)) | ((((uint32_t)f) & 0x1) << 31))
#define MHDR_PPD_TYPEf_GET(r) (((r).mhdr[1]) & 0x7)
#define MHDR_PPD_TYPEf_SET(r,f) (r).mhdr[1]=(((r).mhdr[1] & ~((uint32_t)0x7)) | (((uint32_t)f) & 0x7))
#define MHDR_CCf_GET(r) ((((r).mhdr[1]) >> 3) & 0x3)
#define MHDR_CCf_SET(r,f) (r).mhdr[1]=(((r).mhdr[1] & ~((uint32_t)0x3 << 3)) | ((((uint32_t)f) & 0x3) << 3))
#define MHDR_DPf_GET(r) ((((r).mhdr[1]) >> 6) & 0x3)
#define MHDR_DPf_SET(r,f) (r).mhdr[1]=(((r).mhdr[1] & ~((uint32_t)0x3 << 6)) | ((((uint32_t)f) & 0x3) << 6))
#define MHDR_DROP_REASONf_GET(r) ((((r).mhdr[1]) >> 8) & 0xff)
#define MHDR_DROP_REASONf_SET(r,f) (r).mhdr[1]=(((r).mhdr[1] & ~((uint32_t)0xff << 8)) | ((((uint32_t)f) & 0xff) << 8))
#define MHDR_SRC_PORT_TGIDf_GET(r) ((((r).mhdr[1]) >> 16) & 0x1ff)
#define MHDR_SRC_PORT_TGIDf_SET(r,f) (r).mhdr[1]=(((r).mhdr[1] & ~((uint32_t)0x1ff << 16)) | ((((uint32_t)f) & 0x1ff) << 16))
#define MHDR_DST_PORT_MGIDLf_GET(r) (((r).mhdr[0]) & 0xff)
#define MHDR_DST_PORT_MGIDLf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0xff)) | (((uint32_t)f) & 0xff))
#define MHDR_DST_PORT_MGIDHf_GET(r) ((((r).mhdr[0]) >> 8) & 0xff)
#define MHDR_DST_PORT_MGIDHf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0xff << 8)) | ((((uint32_t)f) & 0xff) << 8))
#define MHDR_TCf_GET(r) ((((r).mhdr[0]) >> 16) & 0xf)
#define MHDR_TCf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0xf << 16)) | ((((uint32_t)f) & 0xf) << 16))
#define MHDR_MCSTf_GET(r) ((((r).mhdr[0]) >> 20) & 0x1)
#define MHDR_MCSTf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0x1 << 20)) | ((((uint32_t)f) & 0x1) << 20))
#define MHDR_EGRESS_TAGGING_STATUSf_GET(r) ((((r).mhdr[0]) >> 21) & 0x1)
#define MHDR_EGRESS_TAGGING_STATUSf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0x1 << 21)) | ((((uint32_t)f) & 0x1) << 21))
#define MHDR_IEUf_GET(r) ((((r).mhdr[0]) >> 22) & 0x1)
#define MHDR_IEUf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0x1 << 22)) | ((((uint32_t)f) & 0x1) << 22))
#define MHDR_IEU_VALIDf_GET(r) ((((r).mhdr[0]) >> 23) & 0x1)
#define MHDR_IEU_VALIDf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0x1 << 23)) | ((((uint32_t)f) & 0x1) << 23))
#define MHDR_STARTf_GET(r) ((((r).mhdr[0]) >> 24) & 0xff)
#define MHDR_STARTf_SET(r,f) (r).mhdr[0]=(((r).mhdr[0] & ~((uint32_t)0xff << 24)) | ((((uint32_t)f) & 0xff) << 24))

/*******************************************************************************
 * End of 'MHDR'
 ******************************************************************************/




/*******************************************************************************
 *
 *                         MHDR SYMBOL TABLE
 *
 ******************************************************************************/

extern bcmdrd_symbols_t mhdr_symbols;


#endif /* BCMPKT_MHDR_DEFS_H */
